---
apiVersion: v1
kind: Namespace
metadata:
  name: pgkube
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: pgkube
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: pgkube
spec:
  serviceName: "postgres-service"
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15
          env:
            - name: POSTGRES_USER
              value: "pgkube-user"
            - name: POSTGRES_PASSWORD
              value: "pgkube-password"
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-pv
              mountPath: /var/lib/postgresql/data
          resources:
            requests:
              memory: "300Mi"
              cpu: "0.1"
  volumeClaimTemplates:
    - metadata:
        name: postgres-pv
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 4Gi
