// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0
// source: query.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const stopOtherPods = `-- name: StopOtherPods :exec
UPDATE pod
SET deleted_at = $1
WHERE deleted_at IS NULL
  AND pod_uid != ALL ($2::uuid[])
`

type StopOtherPodsParams struct {
	DeletedAt      pgtype.Timestamptz
	RunningPodUids []pgtype.UUID
}

func (q *Queries) StopOtherPods(ctx context.Context, arg StopOtherPodsParams) error {
	_, err := q.db.Exec(ctx, stopOtherPods, arg.DeletedAt, arg.RunningPodUids)
	return err
}

const upsertJob = `-- name: UpsertJob :exec
INSERT INTO job(job_uid, name, namespace, labels, annotations, controller_uid, controller_kind, controller_name, created_at,
                deleted_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
ON CONFLICT (job_uid)
    DO UPDATE SET name        = $2,
                  namespace   = $3,
                  labels      = $4,
                  annotations = $5,
                  controller_uid   = $6,
                  controller_kind  = $7,
                  controller_name  = $8,
                  created_at  = $9,
                  deleted_at  = $10
`

type UpsertJobParams struct {
	JobUid         pgtype.UUID
	Name           string
	Namespace      string
	Labels         []byte
	Annotations    []byte
	ControllerUid  pgtype.UUID
	ControllerKind string
	ControllerName string
	CreatedAt      pgtype.Timestamptz
	DeletedAt      pgtype.Timestamptz
}

func (q *Queries) UpsertJob(ctx context.Context, arg UpsertJobParams) error {
	_, err := q.db.Exec(ctx, upsertJob,
		arg.JobUid,
		arg.Name,
		arg.Namespace,
		arg.Labels,
		arg.Annotations,
		arg.ControllerUid,
		arg.ControllerKind,
		arg.ControllerName,
		arg.CreatedAt,
		arg.DeletedAt,
	)
	return err
}

const upsertPod = `-- name: UpsertPod :exec
INSERT INTO pod (pod_uid, name, namespace, node_name, labels, annotations, controller_uid, controller_kind,
                 controller_name, request_cpu_cores, request_memory_bytes, created_at, deleted_at, started_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
ON CONFLICT (pod_uid)
    DO UPDATE SET name                 = $2,
                  namespace            = $3,
                  node_name            = $4,
                  labels               = $5,
                  annotations          = $6,
                  controller_uid            = $7,
                  controller_kind           = $8,
                  controller_name           = $9,
                  request_cpu_cores    = $10,
                  request_memory_bytes = $11,
                  created_at           = $12,
                  deleted_at           = $13,
                  started_at           = $14
`

type UpsertPodParams struct {
	PodUid             pgtype.UUID
	Name               string
	Namespace          string
	NodeName           string
	Labels             []byte
	Annotations        []byte
	ControllerUid      pgtype.UUID
	ControllerKind     string
	ControllerName     string
	RequestCpuCores    float64
	RequestMemoryBytes float64
	CreatedAt          pgtype.Timestamptz
	DeletedAt          pgtype.Timestamptz
	StartedAt          pgtype.Timestamptz
}

func (q *Queries) UpsertPod(ctx context.Context, arg UpsertPodParams) error {
	_, err := q.db.Exec(ctx, upsertPod,
		arg.PodUid,
		arg.Name,
		arg.Namespace,
		arg.NodeName,
		arg.Labels,
		arg.Annotations,
		arg.ControllerUid,
		arg.ControllerKind,
		arg.ControllerName,
		arg.RequestCpuCores,
		arg.RequestMemoryBytes,
		arg.CreatedAt,
		arg.DeletedAt,
		arg.StartedAt,
	)
	return err
}

const upsertReplicaSet = `-- name: UpsertReplicaSet :exec
INSERT INTO replica_set (replica_set_uid, name, namespace, labels, annotations, controller_uid, controller_kind,
                         controller_name, created_at, deleted_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
ON CONFLICT (replica_set_uid)
    DO UPDATE SET name        = $2,
                  namespace   = $3,
                  labels      = $4,
                  annotations = $5,
                  controller_uid   = $6,
                  controller_kind  = $7,
                  controller_name  = $8,
                  created_at  = $9,
                  deleted_at  = $10
`

type UpsertReplicaSetParams struct {
	ReplicaSetUid  pgtype.UUID
	Name           string
	Namespace      string
	Labels         []byte
	Annotations    []byte
	ControllerUid  pgtype.UUID
	ControllerKind string
	ControllerName string
	CreatedAt      pgtype.Timestamptz
	DeletedAt      pgtype.Timestamptz
}

func (q *Queries) UpsertReplicaSet(ctx context.Context, arg UpsertReplicaSetParams) error {
	_, err := q.db.Exec(ctx, upsertReplicaSet,
		arg.ReplicaSetUid,
		arg.Name,
		arg.Namespace,
		arg.Labels,
		arg.Annotations,
		arg.ControllerUid,
		arg.ControllerKind,
		arg.ControllerName,
		arg.CreatedAt,
		arg.DeletedAt,
	)
	return err
}
