name: build
on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.21'
      - name: go test
        working-directory: app
        run: go test -v ./...
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.55.0
          working-directory: app

  build-and-publish-image:
    needs: [test, lint]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Docker login
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Docker build and push (main)
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          docker buildx build \
            --platform=linux/amd64 \
            --push \
            -t ghcr.io/r2k1/pgkube:main \
            .
      - name: Docker build and push (latest)
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        run: |
          tag="$(echo "${{ github.ref }}" | cut -d'/' -f3)"
          docker buildx build \
            --platform=linux/amd64 \
            --push \
            -t ghcr.io/r2k1/pgkube:latest \
            -t ghcr.io/r2k1/pgkube:$tag \
            .
        
